### ISSUE TITLE
Indexes in config

### ISSUE THREAD

**Issue by EmanueleMinotto** [EmanueleMinotto/OpenSearchServerBundle#3]
```yml
open_search_server:
  indexes:
  - foo
  - bar
  - ...
```
